import { Email } from "@/components/EmailItem/types";

export const EMAILS: Email[] = [
  {
    id: "1",
    name: "John Smith",
    avatar: "https://mighty.tools/mockmind-api/content/human/65.jpg",
    marker: "importante",
    subject: "O que é o Lorem Ipsum?",
    message: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
    star: false,
    date: "04 de nov.",
  },
  {
    id: "2",
    name: "Andy Doe",
    avatar: "https://mighty.tools/mockmind-api/content/human/57.jpg",
    subject: "Lorem Ipsum - De onde é que ele vem",
    message: "Ao contrário da crença popular, o Lorem Ipsum não é simplesmente texto aleatório. Tem raízes numa peça de literatura clássica em Latim, de 45 AC, tornando-o com mais de 2000 anos. Richard McClintock, um professor de Latim no Colégio Hampden-Sydney, na Virgínia, procurou uma das palavras em Latim mais obscuras (consectetur) numa passagem Lorem Ipsum, e atravessando as cidades do mundo na literatura clássica, descobriu a sua origem. Lorem Ipsum vem das secções 1.10.32 e 1.10.33 do 'de Finibus Bonorum et Malorum' (Os Extremos do Bem e do Mal), por Cícero, escrito a 45AC. Este livro é um tratado na teoria da ética, muito popular durante a Renascença. A primeira linha de Lorem Ipsum, 'Lorem ipsum dolor sit amet...' aparece de uma linha na secção 1.10.32.",
    star: true,
    date: "01 de nov.",
  },
  {
    id: "3",
    name: "Jane Marker",
    avatar: "https://mighty.tools/mockmind-api/content/human/68.jpg",
    subject: "Porque é que o usamos?",
    message: "É um facto estabelecido de que um leitor é distraído pelo conteúdo legível de uma página quando analisa a sua mancha gráfica. Logo, o uso de Lorem Ipsum leva a uma distribuição mais ou menos normal de letras, ao contrário do uso de 'Conteúdo aqui, conteúdo aqui', tornando-o texto legível. Muitas ferramentas de publicação electrónica e editores de páginas web usam actualmente o Lorem Ipsum como o modelo de texto usado por omissão, e uma pesquisa por 'lorem ipsum' irá encontrar muitos websites ainda na sua infância. Várias versões têm evoluído ao longo dos anos, por vezes por acidente, por vezes propositadamente (como no caso do humor).",
    star: false,
    date: "21 de ago.",
  },
  {
    id: "4",
    name: "Miranda Priestly",
    marker: "importante",
    avatar: "https://mighty.tools/mockmind-api/content/human/43.jpg",
    subject: "Novos horários de trabalho",
    message: "Devido a alta demanda de profissionais de TI no mercado, a partir de hoje...",
    star: false,
    date: "20 de ago.",
  },
  {
    id: "5",
    name: "Jim Halpert",
    avatar: "https://mighty.tools/mockmind-api/content/human/53.jpg",
    subject: "Memorando sobre o dia de hoje",
    message: "É importante lembrar que a partir de hoje nosso gerente e chefe Michael Scott estará sobre...",
    star: true,
    date: "19 de ago.",
  },
  {
    id: "6",
    name: "Pam Beesly",
    avatar: "https://mighty.tools/mockmind-api/content/human/49.jpg",
    subject: "Um pouco sobre Pam Beesly",
    message: "Pamela Morgan Beesly Halpert, mais conhecida como Pam Beesly, é uma personagem fictícia da série de televisão estadunidense The Office",
    star: false,
    date: "19 de ago.",
  },
  {
    id: "7",
    name: "John Smith",
    avatar: "https://mighty.tools/mockmind-api/content/human/75.jpg",
    subject: "Registro de ponto",
    message: "Para garantir que todos os colaboradores estejam cumprindo com a carga horária...",
    star: false,
    date: "18 de ago.",
  },
  
]